### ISSUE TITLE
Fix readme link

### ISSUE THREAD

**Issue by FreePhoenix888** [deep-foundation/capacitor-voice-recorder#3]
https://github.com/deep-foundation/capacitor-voice-recorder#:~:text=%5BIRecord%5D%20%3A%20https%3A//deep%2Dfoundation.github.io/capacitor%2Dvoice%2Drecorder/interfaces/IRecord.html

**Comment by Romanxz** [comment]
But how? I posted about this in discord : https://discord.com/channels/739430470345031692/1123251123545964554/1134150287368667239

**Comment by FreePhoenix888** [comment]
> But how? I posted about this in discord : https://discord.com/channels/739430470345031692/1123251123545964554/1134150287368667239

https://github.com/deep-foundation/capacitor-voice-recorder/commit/4ff117b74676a4eef25b8b83b3fdb1989bcf5ce0
