### ISSUE TITLE
Why is startTime required to stop recording?

### ISSUE THREAD

**Issue by FreePhoenix888** [deep-foundation/capacitor-voice-recorder#5]
Why is startTime required to stop recording?
https://github.com/deep-foundation/capacitor-voice-recorder/blob/4ff117b74676a4eef25b8b83b3fdb1989bcf5ce0/src/stop-recording.ts#L16

**Comment by Romanxz** [comment]
This functions made in such way that stopRecording uploads record and come info right after recording is stopped.  And it should upload start and end timestamps as links values. I personally think that this existing solution is somewhat dumb and crude. I dont like it. It would be great if you can help me with some idea of timestamps but without passing it from function to function.

**Comment by FreePhoenix888** [comment]
> made in such way that stopRecording uploads record and come info right after recording is stopped. And it should upload start and end timestamps as links values. I personally think that this existing solution is somewhat dumb and crude. I dont like it. It would be great if you can help me with some idea of timestamps but without passing it from function to function.

Now I understand. Everything is fine then
